# Generated by Django 3.0.4 on 2020-08-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='member',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(default='', max_length=52),
        ),
    ]
