# Generated by Django 3.0.4 on 2020-08-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
