# Generated by Django 3.0.4 on 2020-08-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
