# Generated by Django 3.0.4 on 2020-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
