# Generated by Django 3.0.4 on 2020-08-27 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_activity',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
