# Generated by Django 3.0.4 on 2020-08-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='release_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
