# Generated by Django 3.0.4 on 2020-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200827_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
